repos:
  - repo: 'https://github.com/psf/black'
    rev: '21.12b0'
    hooks:
      - id: black
        args: ['--target-version', 'py310']
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: '3.9.2'
    hooks:
      - id: flake8
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: 'v0.920'
    hooks:
      - id: mypy
        exclude: 'tests'
  - repo: 'https://github.com/timothycrosley/isort'
    rev: '5.10.1'
    hooks:
      - id: isort 
        args: ['--profile', 'black']
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: 'poetry run pylint'
        language: system
        types: [python]
        exclude: 'tests'
